# Generated by Django 5.2.7 on 2025-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_end_date_userprofile_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filtered_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
