# Generated by Django 5.2.7 on 2025-10-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
