# Generated by Django 5.2.7 on 2025-10-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_investment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together=set(),
        ),
    ]
