# Generated by Django 5.2.7 on 2025-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_investment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
